version: "3.2"
services:
  php:
    build:
      context: './php/'
      args:
        - 'WITH_XDEBUG=true'
    volumes:
      - ./scalar/:/var/www/html/
    networks:
      - scalarnet
    env_file:
      - secrets.env
    environment:
      SCALAR_DB_HOSTNAME: mysql
      SCALAR_DB_USERNAME: scalar
      SCALAR_DB_PASSWORD: scalar
      SCALAR_DB_DATABASE: scalar_store
      SCALAR_ENCRYPTION_KEY: secretkey
      SCALAR_SHASALT: secretsalt
      SCALAR_COOKIE_PREFIX: scalar
      SCALAR_COOKIE_DOMAIN: localhost
      SCALAR_AUTH_PLUGIN: CasAuth
      SCALAR_USE_AUTH_PLUGIN: 1
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_host=host.docker.internal remote_port=9001"
      PHP_IDE_CONFIG: "serverName=scalar-server"
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    networks:
      - scalarnet
    volumes:
      - ./scalar/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    restart: always
    networks:
      - scalarnet
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=scalar
      - MYSQL_PASSWORD=scalar
      - MYSQL_DATABASE=scalar_store
      - MYSQL_HOST=localhost
networks:
  scalarnet:

